---

dnf_packages:
  cli:
    - abcde
    - bandwhich  # atim
    - bash-completion
    - bat
    - bcal
    - borgbackup
    - bottom  # atim
    - dictd
    - dnf-plugin-system-upgrade
    - dnf-utils
    - dua-cli
    - duf
    - eza
    - fd-find
    - fdkaac
    - fdupes
    - ffmpeg
    - figlet
    - fwupd
    - fzf
    - gcc-c++
    - gh  # gh-cli
    - ghostscript
    - git-delta
    - glances
    - glow  # keefle
    - google-cloud-cli  # google-cloud-sdk
    - gron
    - hadolint
    - htop
    - httpie
    - iftop
    - inxi
    - jo
    - jq
    - keychain
    - kubectl  # google-cloud-sdk
    - lame
    - libmp4v2
    - libvirt-client
    - libxcrypt-compat  # google-cloud-sdk
    - mkvtoolnix
    - most
    - msmtp
    - mtr
    - ncdu
    - neofetch
    - nmap
    - nss-tools
    - ocrmypdf
    - openssl
    - p7zip
    - p7zip-plugins
    - par
    - pdfgrep
    - perf
    - podman
    - preload
    - pwgen
    - python3
    - python3-devel
    - rdfind
    - ripgrep
    - ruby
    - ShellCheck
    - stow
    - strace
    - tidy
    - tlp
    - tmux
    - toilet
    - trash-cli
    - tree
    - vagrant
    - vim
    - wget
    - xsel
    - xterm
    - xz
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
  gui:
    - 1password  # 1password-gui
    - alacritty
    - asciinema
    - audacious
    - calibre
    - code  # vscode
    - distrobox
    - flatpak
    - fragments
    - ghostwriter
    - google-chrome-stable  # google-chrome
    - google-noto-emoji-color-fonts
    - google-noto-sans-fonts
    - google-noto-sans-mono-fonts
    - google-noto-serif-fonts
    - keepassxc
    - kitty
    - libreoffice
    - mediawriter
    - nextcloud-client
    - nextcloud-client-nautilus
    - picard
    - remmina
    - seahorse
    - solaar
    - system-config-printer
    - timeshift
    - torbrowser-launcher
    - vlc
  gnome:
    - celluloid
    - geary
    - gedit-plugin-codecomment
    - gedit-plugin-colorpicker
    - gedit-plugin-git
    - gedit-plugin-joinlines
    - gedit-plugin-multiedit
    - gnome-characters
    - gnome-connections
    - gnome-extensions-app
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-gpaste
    - gnome-tweaks
    - gnote
    - gpaste*
    - gthumb
    - hydrapaper
    - libgnome-keyring
    - meld
    - mpv
    - transmission-gtk
